[book]
authors = ["Mouthless Stoat"]
language = "en"
multilingual = false
src = "src"
title = "A Guide to IMF Sigil"
description = "A full guide to making IMF sigil"

[build]
build-dir = ".book"
extra-watch-dirs = ["./preprocessor/"]

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"
additional-css = ["theme/css.css"]

[output.html.code.hidelines]
json= "~"

[preprocessor]
snip = {command = "python ./preprocessor/snip.py"}
inlineHl = {command = "./preprocessor/mdbook-inline-highlighting.exe", default-language = "gd"}
