[book]
authors = ["Mouthless Stoat"]
language = "en"
multilingual = false
src = "src"
title = "A Guide to IMF Sigil"
description = "A full guide to making IMF sigil"

[build]
build-dir = ".book"
extra-watch-dirs = ["./preprocessor/"]

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"
additional-css = ["theme/css.css", "./theme/mdbook-admonish.css", "./theme/customAdmonish.css"]

git-repository-url = "https://github.com/Mouthless-Stoat/sigil101"
edit-url-template = "https://github.com/Mouthless-Stoat/sigil101/edit/main/{path}"

[output.html.code.hidelines]
json= "~"
gd = "~"

[preprocessor]
main = {command = "python ./preprocessor/main.py"}
inline-highlighting = {command = "./preprocessor/mdbook-inline-highlighting.exe", default-language = "gdscript"}


[preprocessor.admonish]
command = "./preprocessor/mdbook-admonish.exe"

[[preprocessor.admonish.custom]]
directive = "activity"
color = "#ffb454"
icon = "./asset/notepad-icon.svg"
aliases = ["act"]
title = "Activites"
