name: Setup mdBook wth plugins (version)
on:
  push:
    branches:
      - main
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jontze/action-mdbook@v3
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          # Optional Plugins have to be enabled with a version
          use-admonish: true
          admonish-version: "~1.15.0"
      - name: Show mdbook version
        run: mdbook --version
      - name: Show admonish version
        run: mdbook-admonish --version
